baseURL = "https://ambye85.github.io/"
languageCode = "en-gb"
title = "Ashley's musings"
theme = "pickle"

# Copyright notice. This is displayer in the footer.
copyright = "Copyright &copy; Ashley Bye"
custom_css = "/static/css/custom.css"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "ambye85"
  github = "ambye85"
  linkedin = "ambye85"
  # Disqus shortname
  disqus = "ambye85-github-io"
  # Google Analytics API key.
  ga_api_key = "UA-141662135-1"
  authorwebsite = "https://ambye85.github.io/"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "A collection of mostly programming related posts."
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
